// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountProducts(ctx context.Context) (int64, error)
	CountProductsBySearch(ctx context.Context, searchQuery string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersBySearch(ctx context.Context, searchQuery string) (int64, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAveragePrice(ctx context.Context) (interface{}, error)
	GetMaxPrice(ctx context.Context) (interface{}, error)
	GetMinPrice(ctx context.Context) (interface{}, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByPriceRange(ctx context.Context, arg ListProductsByPriceRangeParams) ([]Product, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	SearchProductsWithPriceRange(ctx context.Context, arg SearchProductsWithPriceRangeParams) ([]Product, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
